backend:
  type: str
  help: "Backend framework"
  required: true
  choices:
    Rust: rust
    Skip: skip

backend_type:
  when: "{{ backend != 'skip' }}"
  help: "Backend primary target"
  required: true
  type: str
  choices:
    Application: app
    Library: lib

backend_ns:
  when: "{{ backend != 'skip' }}"
  help: Backend package namespace ([ns]-package-name)
  type: str
  required: true
  default: "{{ frontend_ns or project_abbrev }}"
