database:
  help: Database
  required: true
  type: str
  choices:
    GEL: gel
    Postgres: postgres
    Skip: skip

database_host:
  when: "{{ databse != 'skip' }}"
  help: "Databse host"
  required: true
  type: str
  default: |
    {%- if database == 'gel' -%}gel{%- endif -%}
    {%- if database == 'postgres' -%}postgres{%- endif -%}

database_port:
  when: "{{ databse != 'skip' }}"
  help: "Databse port"
  required: true
  type: int
  default: |
    {%- if database == 'gel' -%}5656{%- endif -%}
    {%- if database == 'postgres' -%}5432{%- endif -%}

database_user:
  when: "{{ databse != 'skip' }}"
  type: str
  help: "Databse user"
  default: |
    {%- if database == 'gel' -%}admin{%- endif -%}
    {%- if database == 'postgres' -%}postgres{%- endif -%}
  required: true

database_password:
  when: "{{ databse != 'skip' }}"
  type: str
  help: "Databse password"
  default: "{{ database_user }}"
  required: true

database_name:
  when: "{{ databse != 'skip' }}"
  type: str
  help: "Databse name"
  default: |
    {%- if database == 'gel' -%}main{%- endif -%}
    {%- if database == 'postgres' -%}{{ project_slug }}{%- endif -%}
  required: true
