frontend:
  help: "Frontend framework"
  required: true
  type: str
  choices:
    Angular: angular
    Skip: skip

frontend_toolchain:
  help: "Frontend toolchain"
  required: true
  type: str
  choices: [bun]

frontend_type:
  when: "{{ frontend != 'skip' }}"
  help: "Frontend primary target"
  required: true
  type: str
  choices:
    Application: app
    Library: lib

frontend_ns:
  when: "{{ frontend != 'skip' }}"
  help: Frontend package namespace (@namespace/*)
  type: str
  required: true
  default: "{{ project_abbrev }}"

frontend_style_language:
  when: "{{ frontend != 'skip' }}"
  help: "Frontend style"
  required: true
  type: str
  choices:
    CSS: css
    SCSS: scss

frontend_style_framework:
  when: "{{ frontend_style_language == 'css' }}"
  help: "Frontend style framework"
  required: true
  type: str
  choices:
    Tailwind: tailwind
    Skip: skip
